continue_training: False

learning_rate: 0.1
num_epochs: 100
batch_size: 2
frame_skip: 50

model: 
  name: "UnA-Gen"
  visualize_stats: True
  
  n_training_rays: 4096   # For visualization this should be an exact square
  mapping_dim: 16

loss:
  binary_cross_entropy: False
  binary_cross_entropy_weight: 0.1